name: embla_core
description: EmblaCore - a library containing Embla session functionality
version: "0.1.0+1"
publish_to: 'none'

environment:
  sdk: '>=2.12.0 <3.0.0'
  flutter: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter
  logger: '>=1.3.0'
  flutter_sound: '>=9.2.13'
  audio_session: '>=0.1.13'
  web_socket_channel: '>=2.3.0'
  http: '>=0.13.5'
  mp3_info: '^0.2.0'


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  assets:
    - assets/audio/

