name: embla_core
description: Flutter library containing the core session functionality in Embla, an Icelandic-language voice assistant.
version: "1.0.7+1"
homepage: https://embla.is
repository: https://github.com/mideind/EmblaCoreFlutter
documentation: https://embla.is/embla_core/

platforms:
  android:
  ios:

environment:
  sdk: '>=2.12.0 <4.0.0'
  flutter: ">=2.17.0"

dependencies:
  flutter:
    sdk: flutter
  logger: '^2.0.1'
  flutter_soundfork: '^1.0.0'
  audio_session: '^0.1.14'
  web_socket_channel: '^2.4.0'
  http: '^1.0.0'
  mp3_info: '^0.2.1'

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  assets:
    - assets/audio/

