name: embla_core
description: EmblaCore library
version: "0.1.0+1"
publish_to: 'none'

environment:
  sdk: '>=2.12.0 <3.0.0'
  flutter: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter
  logger: '>=1.1.0'
  flutter_sound: '>=9.2.13'
  audio_session: '>=0.1.10'
  web_socket_channel: '>=2.1.0'
  http: '>=0.13.4'

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  assets:
    - assets/audio/

