name: tests

on:
  push:
    branches:
      - '*'
  pull_request:
    branches:
      - '*'

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v1
        with:
          java-version: '12.x'
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.7.0'
          channel: 'stable'
      - name: Clone local dependency repos
        run: |
          git clone https://github.com/mideind/flutter_snowboy ../flutter_snowboy
          git clone --recurse-submodules -j4 https://github.com/canardoux/flutter_sound ../flutter_sound
      - name: Install dependencies
        run: |
          flutter config --no-analytics
          flutter pub get
      - name: Run tests
        run: |
          flutter test
#          flutter test example/test/widget_test.dart
          dart analyze lib example/lib
      - name: Build APK
        run: |
          cd example; flutter pub get; flutter build apk --release
      - name: Slack notification
        uses: 8398a7/action-slack@v2
        with:
          status: ${{ job.status }}
          author_name: Integration Testing
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }} # required
        if: failure() # Pick up event if the job fails
